<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jai</string>
	</array>
	<key>name</key>
	<string>jai</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#translation_unit</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.jai</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
			</array>
		</dict>
		<key>cast</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.jai</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.jai</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(cast)\s*\((.+?)\)</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#line-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)0[xX][[:xdigit:]]+</string>
					<key>name</key>
					<string>constant.numeric.hexadecimal.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)\d+(?:\.\d+)?</string>
					<key>name</key>
					<string>constant.numeric.decimal.source.jai</string>
				</dict>
			</array>
		</dict>
		<key>enum</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.enum.source.jai</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.enum.source.jai</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*::\s*(enum)\b</string>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_declartion</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_use</string>
				</dict>
			</array>
		</dict>
		<key>function_declartion</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function.source.jai entity.name.function.source.jai</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.jai</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z_]\w*)\b\s*::\s*(inline)?\s*[\(]</string>
		</dict>
		<key>function_use</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.source.jai</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?!(while|for|if|else|return|continue|then|xx|defer|cast|delete|size_of|remove|using|AOS|SOA|inline)\s+)([a-zA-Z_]\w*)\s*[\(]</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#\w*</string>
					<key>name</key>
					<string>keyword.other.directive.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@\S+</string>
					<key>name</key>
					<string>keyword.other.tag.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:if|then|else|for|while|continue|return)\b</string>
					<key>name</key>
					<string>keyword.control.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:delete|xx|size_of|remove|new)\b</string>
					<key>name</key>
					<string>keyword.operator.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:defer|using)\b</string>
					<key>name</key>
					<string>keyword.other.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>---</string>
					<key>name</key>
					<string>keyword.other.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(it|it_index)\b</string>
					<key>name</key>
					<string>keyword.other.source.jai</string>
				</dict>
			</array>
		</dict>
		<key>line-comment</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.source.jai</string>
		</dict>
		<key>new</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.new.source.jai</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.jai</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(new)\s+(\w+)</string>
		</dict>
		<key>storage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:SOA|AOS|inline)\b</string>
					<key>name</key>
					<string>storage.modifier.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:void|string|bool|float|float32|float64|int|u8|u16|u32|u64|s8|s16|s32|s64)\b</string>
					<key>name</key>
					<string>storage.type.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([A-Z][a-z0-9]+)([_][A-Z][a-z0-9]*)*\b</string>
					<key>name</key>
					<string>storage.type.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>".*?"</string>
					<key>name</key>
					<string>string.quoted.double.source.jai</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$\b\w+\b</string>
					<key>name</key>
					<string>storage.type.source.jai</string>
				</dict>
			</array>
		</dict>
		<key>struct</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.struct.source.jai</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.struct.source.jai</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*::\s*(struct)\b</string>
		</dict>
		<key>translation_unit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#new</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cast</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storage</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jai</string>
	<key>uuid</key>
	<string>728cfc9a-25ea-429c-a559-daf7c5d46351</string>
</dict>
</plist>
